<?php

namespace AppBundle\Repository;

/**
 * ShelvingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShelvingRepository extends \Doctrine\ORM\EntityRepository
{
}
